require_relative 'facebook_graph'
fb=FacebookGraph.new("OfficialHumansofIndia","CAACEdEose0cBAOwDmnDzTMRtehaaOisufsxuBtofYXQtOg3aS00LCExJgvxWBYMVCPX1VywZA1JfhRKcdqBNqcQEb0fFSqNYoON2pCT3VfV2jUIm7oZBQqJMWd37qDhyXZBrDXql0KW1ZCZCBiEWhy9ZCZCWiQbxxZBVZCZBgOFQx1zkkZAapZCqFCjV3XDyECpIfUZCmgz5sYWXNgKVRy9ZBc5t7W")
puts fb.getPosts()[0]['text']