require_relative 'facebook_graph'
fb=FacebookGraph.new("humansofnewyork","CAACEdEose0cBAIOwb1QufbKWYXoBvQQGxqkZA9IouhwMhDaLIlAlDWjg98voMudRykJVZBO5UFfIGEufNYZC1mKjK5H8ZAaTbdaF1nZBG4ckSNwsaUwIZAb5jy8M3phIvg6EaSR1GfJntz8UOHV9gj0xPQfYkgZAxrzwcE01qsCXfcJuDkiTUOCaH5MWGUZC1OcJzdrZAVo6XxcUfiAW482uCkl5cEInwMY8ZD")

print fb.savePostsToUser()